language: java
jdk:
  - oraclejdk7
  - openjdk7
env:
  matrix:
    - API_VERSION=2.8
    - API_VERSION=2.8.1
    - API_VERSION=2.8.2
    - API_VERSION=2.8.3

before_script: ./script/before_build.sh

script:
  - mvn package -DGerrit-ApiVersion=$API_VERSION
  - ./script/build.sh $API_VERSION
